name: coronary-prj-env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip
  - pytest
  - numpy
  - matplotlib
  - pydicom
  - scipy
  - scikit-image

  - pip:
      - imageio
