[project]
name = "Coronary_prj"
version = "0.1.0"
description = "Coronary Artery Calcium SaMD Project"
requires-python = ">=3.10"

dependencies = [
    "numpy",
    "torch",
    "matplotlib",
    "openpyxl",
    "forge-utils @ file:///Users/reneeqian/Documents/PythonStuff/Utilities/forge",
]


[tool.pytest.ini_options]
pythonpath = ["src"]
markers = [
  "requirement(id): Traceability requirement ID",
]

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "W", "B", "I"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["ANN", "S"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]